### ISSUE TITLE
Missing libraries on Kicad v5

### ISSUE THREAD

**Issue by coarse** [Maartenwut/plain60-c#1]
![image](https://user-images.githubusercontent.com/13778315/51423166-880d7980-1bf6-11e9-9e49-396b675e3331.png)
`sym-lib-table` does not exist in the repository, so this repository can't work with KiCad v5

**Comment by evyd13** [comment]
That's right, you need KiCad 6 (nightly) to open it. I will change the readme to mention that.

**Comment by evyd13** [comment]
Actually, the problem was the cache file not having the right name. Has been fixed and it should work now. Let me know if it does so I can close this issue.
