### ISSUE TITLE
How can I create a PCB out of this?

### ISSUE THREAD

**Issue by trickplastic** [Maartenwut/plain60-c#3]
I am trying to create a custom keyboard. I am a still a beginner. Could you please point me to somewhere that I can get one of these produced from?

**Comment by evyd13** [comment]
My way of doing things is order the pcbs at jlcpcb, parts at lcsc and solder every component yourself... There's also a possibility for JLC SMT if you know how to export the files, but even then you'll have to solder at least the resonator and USB-C port yourself. If you're able to do that, you could just as easily solder the rest.
